/*
 * =============================================================================
 * FILE: src/lib/constants.mjs
 *
 * DESCRIPTION:
 * A centralized module for exporting shared constants used throughout the
 * session worker application. This approach prevents the use of "magic strings"
 * in the codebase, improving maintainability and reducing the risk of typos.
 * =============================================================================
 */

/**
 * @constant {string} CID_COOKIE - The internal key for the Client ID.
 */
export const CID_COOKIE = 'cID';

/**
 * @constant {string} SID_COOKIE - The internal key for the Session ID.
 */
export const SID_COOKIE = 'sID';

/**
 * @constant {string} EID_COOKIE - The internal key for the Event ID.
 */
export const EID_COOKIE = 'eID';

/**
 * @constant {string} FPID_COOKIE - The internal key for the Fingerprint ID.
 */
export const FPID_COOKIE = 'fpID';

/**
 * @constant {number} STABLE_KEY_LENGTH - The character length of a stable key
 * generated by `createStableDurableObjectKey`. This is used as a reliable
 * signal to differentiate a fingerprint-named DO from a cID-named DO.
 */
export const STABLE_KEY_LENGTH = 16;