# =============================================================================
# FILE: wrangler.toml
#
# DESCRIPTION:
# Configuration for the standalone, reusable session management worker.
# =============================================================================

name = "divortio-session-worker"
main = "src/worker.mjs"
compatibility_date = "2025-08-22"
compatibility_flags = ["rpc"] # Enable the RPC API

workers_dev = false
minify = true

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1

# --- Environment Variables ---
[vars]
# Inactivity timeout for a session to be considered "expired" on the server-side.
SESSION_TIMEOUT_MS = 1800000 # 30 minutes

# --- Cookie Naming & Domain Configuration ---
COOKIE_APP_PREFIX = ""
SERVER_COOKIE_PREFIX = "_ss_"
CLIENT_COOKIE_PREFIX = "_cs_"
COOKIE_DOMAIN = ""

# --- Cookie Keys Configuration ---
CID_COOKIE_NAME = "cID"
SID_COOKIE_NAME = "sID"
EID_COOKIE_NAME = "eID"
FPID_COOKIE_NAME = "fpID"

# --- Cookie Expiration Settings (in seconds) ---
SESSION_COOKIE_EXPIRATION_SECONDS = 31536000 # 1 year
FP_ID_EXPIRATION_SECONDS = 31536000 # 1 year

# --- Durable Object Garbage Collection ---
DO_TTL_SECONDS = 7776000 # 90 days


# --- Durable Object Bindings ---
[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDO"

# --- Analytics Engine Bindings ---
# Dataset of 1 event per new client (cID)
[[analytics_engine_datasets]]
binding = "STATS_CLIENT"
dataset = "SESSION_CLIENTS"

# Dataset of 1 event per new session (sID)
[[analytics_engine_datasets]]
binding = "STATS_SESSION"
dataset = "SESSION_SESSIONS"

# Dataset of 1 event per new event (eID)
[[analytics_engine_datasets]]
binding = "STATS_EVENTS"
dataset = "SESSION_EVENTS"


# --- Database Migrations ---
[[migrations]]
tag = "v1-initial-install"
new_sqlite_classes = ["SessionDO"]